version: 0.1.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015 Preview
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
on_success:
- ps: |
    $version = $env:APPVEYOR_BUILD_VERSION.Split(".")
    if ($env:APPVEYOR_REPO_TAG -eq $true)
    {
        $version = $version[0] + "." + $version[1] + "." + $version[2]
    }
    else
    {
       $version = $version[0] + "." + $version[1] + "." + $version[2] + "-pre" + $version[3].PadLeft(5,'0')
    }
    nuget pack .\TileProj.nuspec -NonInteractive -Version $version
    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
